#!/usr/bin/env bash
# Sync vendored libsodium source from IntersectMBO/libsodium into
# ClibsodiumLinuxSource/, matching the upstream tree layout. Used by the Linux
# build path for swift-tools-version 6.0 (where SE-0435 staticLibrary artifact
# bundles aren't available — Swift 6.2+ uses Clibsodium.artifactbundle/ instead).
#
# Usage:
#   scripts/sync-libsodium-source.sh [/path/to/IntersectMBO-libsodium-checkout]
#
# Defaults to /Users/hadderley/Projects/Github/IntersectMBO/libsodium.
# Records the upstream commit at ClibsodiumLinuxSource/UPSTREAM_COMMIT.

set -euo pipefail

UPSTREAM="${1:-/Users/hadderley/Projects/Github/IntersectMBO/libsodium}"
DEST_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$DEST_ROOT/ClibsodiumLinuxSource"

if [[ ! -d "$UPSTREAM/src/libsodium" ]]; then
  echo "Not a libsodium checkout: $UPSTREAM" >&2
  echo "Pass the path as the first argument." >&2
  exit 2
fi

UPSTREAM_COMMIT="$(git -C "$UPSTREAM" rev-parse HEAD)"
echo "Syncing from $UPSTREAM @ $UPSTREAM_COMMIT"

# Fresh start — wipe and re-copy so dropped files upstream stay dropped.
rm -rf "$DEST"
mkdir -p "$DEST"

# Copy the entire src/libsodium tree, then prune what we don't compile.
cp -R "$UPSTREAM/src/libsodium/." "$DEST/"

# Drop dirs that contain hand-rolled assembly or CPU-specific SIMD intrinsics.
# SwiftPM has no clean way to assemble .S files conditionally on host arch, and
# the runtime CPU dispatch in sodium/runtime.c will simply route to the portable
# fallback when these implementations aren't compiled in.
for d in \
  crypto_stream/salsa20/xmm6 \
  crypto_stream/salsa20/xmm6int \
  crypto_scalarmult/curve25519/sandy2x \
  crypto_aead/aes256gcm/aesni \
  crypto_aead/aegis256/aesni \
  crypto_aead/aegis256/armcrypto \
  crypto_onetimeauth/poly1305/sse2 \
  crypto_pwhash/scryptsalsa208sha256/sse \
; do
  if [[ -d "$DEST/$d" ]]; then
    rm -rf "$DEST/$d"
  fi
done

# Drop the build-artifact and autotools cruft that came along with cp -R.
find "$DEST" -type d \( -name ".deps" -o -name ".libs" \) -exec rm -rf {} + 2>/dev/null || true
find "$DEST" -type f \( -name "*.o" -o -name "*.lo" -o -name ".dirstamp" -o -name "Makefile" -o -name "Makefile.am" -o -name "Makefile.in" -o -name "*.la" \) -delete 2>/dev/null || true

# version.h is normally generated by ./configure from version.h.in. Use the
# version known to match the Clibsodium.artifactbundle prebuilt .a files
# (1.0.18, what IntersectMBO/libsodium tracks at the pinned commit).
cat > "$DEST/include/sodium/version.h" <<'EOF'
#ifndef sodium_version_H
#define sodium_version_H

#include "export.h"

#define SODIUM_VERSION_STRING "1.0.18"

#define SODIUM_LIBRARY_VERSION_MAJOR 10
#define SODIUM_LIBRARY_VERSION_MINOR 3


#ifdef __cplusplus
extern "C" {
#endif

SODIUM_EXPORT
const char *sodium_version_string(void);

SODIUM_EXPORT
int         sodium_library_version_major(void);

SODIUM_EXPORT
int         sodium_library_version_minor(void);

SODIUM_EXPORT
int         sodium_library_minimal(void);

#ifdef __cplusplus
}
#endif

#endif
EOF

# Remove the now-stale .in template so SwiftPM doesn't see it.
rm -f "$DEST/include/sodium/version.h.in"

# Record provenance.
echo "$UPSTREAM_COMMIT" > "$DEST/UPSTREAM_COMMIT"

echo "Done. ClibsodiumLinuxSource/ now mirrors IntersectMBO/libsodium @ $UPSTREAM_COMMIT minus asm/SIMD dirs."
echo "Source file counts:"
echo "  .c: $(find "$DEST" -name "*.c" | wc -l | tr -d ' ')"
echo "  .h: $(find "$DEST" -name "*.h" | wc -l | tr -d ' ')"
